### ISSUE TITLE
Please consider using event pages instead of background pages

### ISSUE THREAD

**Issue by okgoogle** [p3lim/google-image-search#1]
Link:https://developer.chrome.com/extensions/event_pages
I have modified a version like this,for reference purposes only,good luck!

context.js:

``` javascript
chrome.contextMenus.onClicked.addListener(function (info, tab){
                var src = info.srcUrl;
                var url = 'https://www.google.com/searchbyimage?image_url=';
                if(src.indexOf('data:') != 0){
                        chrome.tabs.create({
                                'url': url + encodeURIComponent(src),
                                'index': tab.index + 1,
                        });        
                }    
});

chrome.contextMenus.create({"title": "Google search by image", "contexts": ["image"], "id": "contextMenu"});
```

manifest.json:

``` json
{
   "background": {
      "persistent": false,
      "scripts": [ "context.js" ]
   },
   "description": "Quickly search by image using Google",
   "icons": {
      "16": "icon.png"
   },
   "manifest_version": 2,
   "name": "Image Search",
   "permissions": [ "contextMenus" ],
   "update_url": "http://clients2.google.com/service/update2/crx",
   "version": "2.0"
}
```

**Comment by p3lim** [comment]
Please provide me with some information why this should be used over the current method, I don't see any reason as to why I would need to change it.

**Comment by okgoogle** [comment]
Link:https://developer.chrome.com/extensions/event_pages
The page show the information:

Event Pages

A common need for apps and extensions is to have a single long-running script to manage some task or state. Event pages to the rescue. Event pages are loaded only when they are needed. When the event page is not actively doing something, it is unloaded, freeing memory and other system resources.

Any way,you can compare two versions while openning and 
Observe the Chrome's Task Manager.

**Comment by p3lim** [comment]
Convincing enough, thanks for the links and details.

**Comment by p3lim** [comment]
e0512c6958b2dd01d7c7746f4e519a318bfc9c67
