### ISSUE TITLE
Extension doesn't open new tab on some images

### ISSUE THREAD

**Issue by Kanro-Code** [p3lim/google-image-search#2]
Example:
http://www.movieposterdb.com/Poster/cda05e7a#

When clicking on the poster in this example and making it fullscreen the extension will not work properly. It does not open a new google images tab. The built-in chrome image searcher does work properly.

I have had this issue a few times before, but this is the only one that I could be arsed writing about :D

**Comment by p3lim** [comment]
The extension does not support raw images (base64), I'll take a look into it.
