### ISSUE TITLE
Not appearing

### ISSUE THREAD

**Issue by ziaul808** [p3lim/google-image-search#3]
When clicking Right mouse keeping on the picture opened in browser the search option is not appearing in the drop down menu

**Comment by p3lim** [comment]
I disbanded this extension a long time ago, currently using [TinEye](https://chrome.google.com/webstore/detail/tineye-reverse-image-sear/haebnnbpedcbhciplfhjjkbafijpncjl?hl=en) instead.
If you still prefer to use Google, the [original extension](https://chrome.google.com/webstore/detail/search-by-image-by-google/dajedkncpodkggklbegccjpmnglmnflm?hl=en) should still work.
